name: Docker build

# This triggers the action when a push is made to the 'main' branch
on:
  push:
    branches:
      - main
      - ci
    tags:
      - '*' 

jobs:
  build-app:
    runs-on: ubuntu-22.04
    container:
      image: docker:dind
    environment: DOCKER_PASSWORD
    # Specify the architecture for ARM64
    strategy:
      matrix:
        arch: [amd64, arm64]
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Pull latest Docker image
      run: |
        docker pull --platform=arm64 ros:humble
        docker pull --platform=amd64 ros:humble

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/arm64, linux/amd64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build backend
      run: |
        if [[ -z ${{  github.ref_name }} ]]; then
          TAG_NAME="latest"  # Use tag name from Git if it's a tag push
        else
          TAG_NAME="${{  github.ref_name }}"  # Default to 'latest' if not a tag
        fi
        echo "Building Docker image with tag: ${TAG_NAME}"
        docker buildx build \
          --push \
          --tag braoutch/ros2-wave-rover:${TAG_NAME} \
          --platform linux/amd64,linux/arm64 . 